version: 0.2

phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Building code...
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Running the terraform plan...
      - ./run.sh
